

```{r}
library(tidyverse)
theme_set(theme_light())
```

```{r}
brewing_materials <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-31/brewing_materials.csv')
beer_taxed <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-31/beer_taxed.csv')
brewer_size <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-31/brewer_size.csv')
beer_states <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-31/beer_states.csv')
```


```{r}
glimpse(brewing_materials)
glimpse(beer_taxed)
glimpse(brewer_size)
glimpse(beer_states)
```



```{r}
brewing_materials %>% 
  filter(year == max(year), month == max(month)) %>% 
  ggplot(aes(y = type, x = month_current)) + 
  geom_col()
```


```{r}
brewing_materials %>% 
  filter(year == max(year), month == max(month)) %>%
  filter(!str_detect(type, "Total")) %>% 
  mutate(type = fct_reorder(type, month_current)) %>% 
  ggplot(aes(y = type, x = month_current)) + 
  geom_col(aes(fill = type), show.legend = FALSE)
```

```{r}
brewing_materials %>% 
  count(data_type)

library(lubridate)

brewing_materials <- brewing_materials %>% 
  mutate(date = str_c(year, month, 1, sep = " ") %>% ymd()) %>% 
  select(-data_type, -year, -month) %>% 
  filter(!str_detect(type, "total")) 



# there seems to be some anomalies in recent 2 years  
brewing_materials %>%
  ggplot(aes(date, month_current)) + 
  geom_line(aes(color = type, group = type))
```

```{r, fig.width = 10, fig.height = 10}
brewing_materials <- brewing_materials %>% filter(year(date) < 2016)


ggplot(brewing_materials) + 
  geom_col(aes(date, month_current, fill = type)) +
  scale_y_continuous(labels = label_number_si()) + 
  theme(legend.position = "bottom")
```

